# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/front"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000 #Add a limit for number of pull request to 1000 (0 will disable this module)
    milestone: 1 #Add a group for pull request
    target-branch: "develop" #target branch to check update of dependencies et pull request on this branch

    # Enable version updates for Docker
  - package-ecosystem: "maven"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/api"
    # Check for updates once a week
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000 #Add a limit for number of pull request to 1000 (0 will disable this module)
    milestone: 2 #Add a group for pull request
    target-branch: "develop" #target branch to check update of dependencies et pull request on this branch
    
      # # Enable version updates for Docker
  # - package-ecosystem: "docker"
    # # Look for a `Dockerfile` in the `root` directory
    # directory: "/api"
    # # Check for updates once a week
    # schedule:
      # interval: "daily"
