# This is a basic workflow to help you get started with Actions

name: Angular Building Checker

# Controls when the workflow will run
on: [workflow_dispatch, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: npm install
        working-directory: ./front
        run: npm install
        
      - name: npm run build
        working-directory: ./front
        run: npm run build

  merge:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: pr-${{ github.event.number }}
        timeout: 8m
    
    - name: comment PR
      uses: okteto/notify-pr@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://movies-pr-${{ github.event.number }}-cindylopez.cloud.okteto.net"
