# This is a basic workflow to help you get started with Actions

name: Angular Building Checker

# Controls when the workflow will run
on: [workflow_dispatch, pull_request]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: npm install
        working-directory: ./front
        run: npm install
        
      - name: npm run build
        working-directory: ./front
        run: npm run build

  merge:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: PR Merge
      # You may pin to the exact commit or the version.
      # uses: actions-cool/pr-merge@fe1e933579252a77a59d3e9c21cfa3f184cd2c65
      uses: actions-cool/pr-merge@v0.0.1-beat
      with:
        # Secret GitHub API token to use for making API requests.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
