# This is a basic workflow to help you get started with Actions

name: Angular Building Checker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: npm install
        working-directory: ./front
        run: npm install
        
      - name: npm run build
        working-directory: ./front
        run: npm run build

  merge:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Notify PR
        # You may pin to the exact commit or the version.
        # uses: okteto/notify-pr@1372ddd587e781f2f995b1f612221f039cfedc50
        uses: okteto/notify-pr@v1.0
        with:
          GITHUB_TOKEN: AUTOCOMMENTPRWITHACTION
          # The message
          message: Nice PR !
